name: TomLuke
favicon: null
layout_spectrum: 0.44380183704197407
typography_spectrum: 0.4083693919237703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6183028751984239
  lightness: 0.9290472667198628
  saturation: 0.05501354788430035
  rhythmicContrast: 0.00081245182082057
purpose: []
