favicon: null
name: TomLuke
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 1
  rhythmicContrast: 0.0008124518
  brandColors:
    - '#CDBFAB'
    - '#393731'
    - '#FFFFFF'
    - '#804249'
    - '#C68976'
  lightness: 0.9290473
typography_spectrum: 0.3968851
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4438018370419741
analytics:
  twitter: null
  google: null
  facebook: null
